<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PantryCloud.Recipe.Application\PantryCloud.Recipe.Application.csproj" />
    <ProjectReference Include="..\PantryCloud.Recipe.Core\PantryCloud.Recipe.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
