<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PantryCloud.Notification.Core\PantryCloud.Notification.Core.csproj" />
    <ProjectReference Include="..\..\PantryCloud.Household\PantryCloud.Household.Application\PantryCloud.Household.Application.csproj" />
    <ProjectReference Include="..\..\PantryCloud.Pantry\PantryCloud.Pantry.Application\PantryCloud.Pantry.Application.csproj" />
    <ProjectReference Include="..\..\PantryCloud.ShoppingList\PantryCloud.ShoppingList.Application\PantryCloud.ShoppingList.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PantryCloud.SharedKernel\PantryCloud.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.2" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

