<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PantryCloud.Pantry.Application\PantryCloud.Pantry.Application.csproj" />
    <ProjectReference Include="..\PantryCloud.Pantry.Core\PantryCloud.Pantry.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
