name: CI/CD - AuditService

on:
  push:
    branches:
      - develop
    paths:
      - 'src/Services/PantryCloud.Audit/**'
      - 'src/BuildingBlocks/**'
      - 'test/PantryCloud.Audit/**'
      - '.github/workflows/audit.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'src/Services/PantryCloud.Audit/**'
      - 'src/Services/PantryCloud.Household/PantryCloud.Household.Application/**'
      - 'src/Services/PantryCloud.Pantry/PantryCloud.Pantry.Application/**'
      - 'src/Services/PantryCloud.ShoppingList/PantryCloud.ShoppingList.Application/**'
      - 'src/BuildingBlocks/**'
      - 'test/PantryCloud.Audit/**'
      - '.github/workflows/audit.yml'
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/base.yml
    with:
      service_project_path: src/Services/PantryCloud.Audit/PantryCloud.Audit.Presentation/PantryCloud.Audit.Presentation.csproj
      unit_test_project_path: test/PantryCloud.Audit/PantryCloud.Audit.UnitTests/PantryCloud.Audit.UnitTests.csproj
      integration_test_project_path: test/PantryCloud.Audit/PantryCloud.Audit.IntegrationTests/PantryCloud.Audit.IntegrationTests.csproj
      dockerfile_path: src/Services/PantryCloud.Audit/PantryCloud.Audit.Presentation/Dockerfile
      image_name: samanekj/auditservice
      coverage_flag: audit-service
      test_results_name: "AuditService - Test Results"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
