{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pantry-microservice.fullname" . }}
  labels:
    {{- include "pantry-microservice.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pantry-microservice.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.hpa.maxPodScalingPerPeriod }}
          periodSeconds: {{ .Values.hpa.scalingPeriodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.hpa.maxPodScalingPerPeriod }}
          periodSeconds: {{ .Values.hpa.scalingPeriodSeconds }}
{{- end }}
